### ISSUE TITLE
Peer-To-Peer Code Review Week 4: Day 5

### ISSUE THREAD

**Issue by JEFFKAY16** [Meri-MG/Portfolio#14]
## Peer-To-Peer Code Review Week 4: Day 5

Hi Meri, excellent work so far- keep going. Like always, code reviews help us improve and as a group, we have opened an issue pointing out items we think can be **improved** here below: 

- The `ul` tag [here](https://github.com/Meri-MG/Portfolio-Microverse/blob/caebb80d9d30ae89f512c4e9867c2e78f594f4c6/index.html#L38) looks astray, kindly indent it. 
- The closing `</div>` looks astray as well, I can barely tell where its origin is. Make reference [here](https://github.com/Meri-MG/Portfolio-Microverse/blob/caebb80d9d30ae89f512c4e9867c2e78f594f4c6/index.html#L85)
- The `README.md` file can be improved by using two(2) images: Mobile and Desktop versions.
- You can also add a brief introduction to your `README.md` file at the beginning.

**Comment by Meri-MG** [comment]
Thanks for pointing out these isuues. Changes were made in html and readme files.
