### ISSUE TITLE
Morning code review

### ISSUE THREAD

**Issue by GintsM** [Meri-MG/Portfolio#2]
My suggestions to improve. 
In main section you use line 15 and 16 div tag like a wrapper  for header,  But you could use header by it self as a wrapper. Avoiding extra line. The same for class="works-wrapper"  you use that as a wrapper, but then just make a section also as wrapper line 80 and 81.
In lines 26 and 27 you could use article tag for wrapping in it would be more semantic

**Comment by mprotic123** [comment]
Hello Meri, I have only one suggestion for you to improve it. Please make your website a little bit more responsive when we are talking about width. This is important to do not just because of the design but because of a wide spectrum of devices. Thanks! 😄

**Comment by Wes-Isaac** [comment]
Hi Meri, I think the project is great, one thing I would suggest is that you edit your README file so that it will look more professional. Other than that and the comments above, it looks great. Thanks 😁

**Comment by Meri-MG** [comment]
Thanks for pointing out these issues.
- The div tags were replaced with semantic tags respectively.
- The page was made responsive for all resolutions.
- The readme file was updated.
